# General app config settings for the resque worker.
# Be sure to restart the worker when you change these settings:
# `sudo god restart resque`
---
# Directory to log into. Will create if able
log_file: /mnt/log/nagios_automation.log

# Level to log at. Available levels:
# debug, info, warn, error, fatal
log_level: info

# Directory to write the generated config files into. Will create if able.
output_dir: /etc/nagios3/conf.d/auto

# Write out a config file even if there's already a file with that name
allow_overwrites: false

# Enable or disable sending emails for erors
email_alerts: true

# List of email addresses to send alerts to
# TODO: Make this system more robust with error levels, etc
# TODO: Look into a logger that will send emails on log events automatically
emails:
  - josh@cloudspace.com
  - mcupples@cloudspace.com

