# Simple YAML structure mapping recipe and role names to check (service) names.
# Expressed in a simple tuple format:
# -
#   - <Check description>
#   - <Check command>
---
# Checks to put on every node.
basic_checks:
  - 
    - "Free Memory"
    - "check_mem"
  - 
    - "Load Average"
    - "check_load"
  - 
    - "Ping check"
    - "check_ping!100.0,20%!500.0,60%"
  - 
    - "SSH Check"
    - "check_ssh"
  - 
    - "Free Space All Disks"
    - "check_all_disks"

# Matching recipes namespace. Put definitions here to match eg. "recipe[nginx]" as a run_list item.
recipe:
  nginx: &nginx
    -
      - "Nginx Running"
      - "check_nginx"
    -
      - "HTTP Check: %{node_name}"
      - "http_check!%{local_ipv4}"
  memcached: &memcached
    -
      - "Memcached Running"
      - "check_memcached"
  postfix: &postfix
    -
      - "Postfix Running"
      - "check_postfix"
  apache2: &apache2
    -
      - "Apache Running"
      - "check_apache"
    -
      - "HTTP Check: %{node_name}"
      - "http_check!%{local_ipv4}"
  "mongodb::mongos": &mongos
    -
      - "Mongos Check"
      - "check_mongos"
  "mongodb::shard": &mshard
    -
      - "Mongo Shard Check"
      - "check_mongo_shard"
  "mongodb::config": &mconfig
    -
      - "Mongo Config Check"
      - "check_mongo_config"
    

# Matching roles namespace. Put definitions here to match eg. "role[rails_web]" as a run_list item.
role:
  production: &production
    *memcached
  "web-php": &webphp
    [ *production, *apache2, *postfix, *mongos ]
  gearman:
    *webphp
  mongo:
    [ *production, *mshard, *mconfig ]


# Ignored namespace. Definitions put here will be ignored, so unmonitorable recipes won't raise warnings.
# NOTE: Definitions put here will be ignored EVEN IF THEY ALSO EXIST ABOVE.
ignored:
  recipe:
    - "aws"
    - "apt"
    - "git"
    - "xfs"
    - "apparmor"
    - "onetruefan::zend"
    - "application"

  role:
    - "nagios-register-test"

